// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhdpsdpgxkfvzwypgxgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhoZHBzZHBneGtmdnp3eXBneGdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExODI5NzEsImV4cCI6MjA1Njc1ODk3MX0.NB7gQ1lpUX5oYBNtHo87TC3xSjxYCpuyPhC_f99YWmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);